ls
pip list
pip install osgeo
pip install gdal
/bin/python3 /root/Profiles/vehicle_control/RoverSearch/heightMap.py
cd Profiles/vehicle_control/RoverSearch/
/bin/python3 /root/Profiles/vehicle_control/RoverSearch/heightMap.py
ls
/bin/python3 /root/Profiles/vehicle_control/RoverSearch/heightMap.py
cd /root/Profiles/ProfileScripts/Vehicle/
ls
cp Samples/startRoverSearch.sh startVehicle.sh
cd /
cd ~
./reset.sh 
ls
chmod +X tail_vehicle_log.sh 
ls
chmod +x tail_vehicle_log.sh 
ls
./tail_vehicle_log.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
clear
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
ls
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
clear
./stopexperiment.sh 
./reset.sh 
clear
./startexperiment.sh 
./tail_vehicle_log.sh 
./stopexperiment.sh 
./reset.sh 
